Repository NativeScript/ios-runtime, pull requests merged in 2018-06, with the labels that each got.

#928 fix(debug): Close dispatch_io when disconnecting inspector
  src/debugging/TNSDebugging.h
Labels: bug, os: ios

#943 docs: Update Changelog for 4.1.1
  CHANGELOG.md
Labels: docs

#949 chore: Move clang modules and auto link frameworks flags to build.xcc…
  build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
  build/project-template/__PROJECT_NAME__/build.xcconfig
Labels: os: ios
