Repository NativeScript/ios-runtime, pull requests merged in 2019-03, with the labels that each got.

#1086 fix(runtime): Respect availability attributes for protocols and base classes
  src/NativeScript/GlobalObject.mm
  src/NativeScript/Metadata/Metadata.h
  src/NativeScript/Metadata/Metadata.mm
  src/NativeScript/ObjC/Constructor/ObjCConstructorBase.mm
  src/NativeScript/ObjC/Constructor/ObjCConstructorNative.mm
  src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.h
  src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm
  src/NativeScript/ObjC/ObjCMethodCall.h
  src/NativeScript/ObjC/ObjCMethodCall.mm
  src/NativeScript/ObjC/ObjCMethodCallback.mm
  src/NativeScript/ObjC/ObjCProtocolWrapper.mm
  src/NativeScript/ObjC/ObjCPrototype.h
  src/NativeScript/ObjC/ObjCPrototype.mm
  src/NativeScript/TypeFactory.mm
  tests/TestFixtures/Api/TNSVersions.h
  tests/TestFixtures/Api/TNSVersions.m
  tests/TestFixtures/Interfaces/TNSConstructorResolution.h
  tests/TestFixtures/Interfaces/TNSConstructorResolution.m
  tests/TestFixtures/Interfaces/TNSInheritance.h
  tests/TestFixtures/Interfaces/TNSInheritance.m
  tests/TestRunner/app/ApiTests.js
  tests/TestRunner/app/Inheritance/InheritanceTests.js
  tests/TestRunner/app/ObjCConstructors.js
  tests/TestRunner/app/VersionDiffTests.js
Labels: bug, cla: yes

#1089 Use the same method for console.log and console.trace
  src/NativeScript/inspector/GlobalObjectConsoleClient.cpp
Labels: cla: yes

#1088 chore: Speed up Jenkins build
  build/TestRunner.xcscheme
  build/scripts/build-metadata-generator.sh
  build/scripts/build-nativescript-framework.sh
  build/scripts/build-testrunner-application.sh
  build/scripts/common.sh
  launch-c.in
  launch-cxx.in
  src/NativeScript/CMakeLists.txt
  tests/TestFixtures/CMakeLists.txt
Labels: cla: yes, improvement

#1092 fix(runtime): Expose base class missing properties in inheritors
  src/NativeScript/GlobalObject.mm
  src/NativeScript/ObjC/ObjCPrototype.h
  src/NativeScript/ObjC/ObjCPrototype.mm
  tests/TestRunner/app/ApiTests.js
Labels: bug, cla: yes, regression

#1101 Fix breakpoints in onNavigatingTo and add stacktrace to console.trace() message
  src/NativeScript/inspector/GlobalObjectConsoleClient.cpp
  src/debugging/TNSDebugging.h
Labels: cla: yes

#1102 chore: add info about a string hardcoded in the CLI
  src/NativeScript/JSErrors.mm
Labels: cla: yes

#1103 fix(build): Fix WebKit project generation errors with CMake 3.14
  README.md
  src/WebKit.cmake
Labels: bug, cla: yes

#1107 chore: Release notes for version 5.3.0
  CHANGELOG.md
Labels: cla: yes, docs

#1108 fix(livesync): `__onLiveSync` function must be called on the UI thread
  build/scripts/build-testrunner-application.sh
  cmake/CreateNativeScriptApp.cmake
  src/NativeScript/CMakeLists.txt
  src/NativeScript/inspector/InspectorPageAgent.mm
Labels: bug, cla: yes, regression
