Repository NativeScript/ios-runtime, pull requests merged in 2019-11, with the labels that each got.

#1224 fix(project-template): Remove build scripts from target
  build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
Labels: bug, cla: yes, improvement

#1226 fix(runtime): Do not hide property with more accessors
  plugins/TKLiveSync/Podfile.lock
  src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm
  src/NativeScript/ObjC/ObjCPrototype.mm
  tests/TestFixtures/Interfaces/TNSMethodCalls.h
  tests/TestFixtures/Interfaces/TNSMethodCalls.m
  tests/TestRunner/app/Inheritance/InheritanceTests.js
Labels: bug, cla: yes

#1229 fix(runtime): Exclude duplicate properties from getOwnPropertyNames' result
  src/NativeScript/ObjC/ObjCPrototype.h
  src/NativeScript/ObjC/ObjCPrototype.mm
  tests/TestRunner/app/Inheritance/InheritanceTests.js
Labels: bug, cla: yes, regression

#1230 fix: don't crash app if flag is present
  src/NativeScript/JSErrors.mm
Labels: cla: yes
