Repository NativeScript/ios-runtime, pull requests merged in 2019-12, with the labels that each got.

#1236 fix(metadata-generator): Respect CLANG_ENABLE_MODULES
  build/scripts/build-step-metadata-generator.py
Labels: bug, cla: yes, improvement

#1240 fix: make the pbxproject fastlane compatible
  build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
Labels: cla: yes

#1241 fix(runtime): Correctly retrieve discarded exceptions flag
  src/NativeScript/JSErrors.mm
Labels: bug, cla: yes

#1243 fix: wrong automatic signing configuration
  build/project-template/__PROJECT_NAME__.xcodeproj/project.pbxproj
Labels: bug, cla: yes, regression
