Repository NativeScript/ios-runtime, pull requests merged in 2019-08, with the labels that each got.

#1179 fix(project-template): Correctly get architecture in `nsld` with Xcode 11
  build/project-template/internal/nsld.sh
Labels: bug, cla: yes

#1190 refactor: improve stackTrace for readability
  src/NativeScript/JSErrors.mm
Labels: cla: yes

#1183 chore(Gameraww): Fix crash on startup
  examples/Gameraww/app/DetailViewController.js
  src/NativeScript/ObjC/ObjCMethodCallback.mm
  tests/TestRunner/app/Inheritance/InheritanceTests.js
Labels: bug, cla: yes

#1191 feat: support app refresh through the notifications service
  src/debugging/TNSDebugging.h
Labels: cla: yes

#1193 fix: Improve error messages thrown by iOS runtime
  src/NativeScript/Calling/FFICall.h
  src/NativeScript/GlobalObject.mm
  src/NativeScript/GlobalObject.moduleLoader.mm
  src/NativeScript/Interop.mm
  src/NativeScript/Marshalling/FunctionReference/FunctionReferenceConstructor.cpp
  src/NativeScript/Marshalling/FunctionReference/FunctionReferenceTypeInstance.cpp
  src/NativeScript/Marshalling/Fundamentals/FFIPrimitiveTypes.cpp
  src/NativeScript/Marshalling/Pointer/PointerConstructor.cpp
  src/NativeScript/Marshalling/Pointer/PointerInstance.cpp
  src/NativeScript/Marshalling/Pointer/PointerInstance.h
  src/NativeScript/Marshalling/Record/RecordConstructor.cpp
  src/NativeScript/Marshalling/Reference/ExtVectorTypeInstance.cpp
  src/NativeScript/Marshalling/Reference/IndexedRefTypeInstance.cpp
  src/NativeScript/Marshalling/Reference/ReferenceTypeInstance.cpp
  src/NativeScript/Metadata/Metadata.h
  src/NativeScript/Metadata/Metadata.mm
  src/NativeScript/ObjC/Block/ObjCBlockType.mm
  src/NativeScript/ObjC/Constructor/ObjCConstructorBase.mm
  src/NativeScript/ObjC/Constructor/ObjCConstructorNative.mm
  src/NativeScript/ObjC/Enumeration/ObjCFastEnumerationIterator.mm
  src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.h
  src/NativeScript/ObjC/Inheritance/ObjCClassBuilder.mm
  src/NativeScript/ObjC/Inheritance/ObjCExtend.mm
  src/NativeScript/ObjC/ObjCMethodCallback.h
  src/NativeScript/ObjC/ObjCMethodCallback.mm
  src/NativeScript/ObjC/ObjCPrimitiveTypes.mm
  src/NativeScript/ObjC/ObjCPrototype.mm
  src/NativeScript/Runtime/JSWeakRefConstructor.cpp
  src/NativeScript/Runtime/JSWeakRefPrototype.cpp
  tests/TestFixtures/Interfaces/TNSConstructorResolution.h
  tests/TestFixtures/Interfaces/TNSConstructorResolution.m
  tests/TestRunner/app/ApiTests.js
  tests/TestRunner/app/Inheritance/InheritanceTests.js
  tests/TestRunner/app/Marshalling/FunctionPointerTests.js
  tests/TestRunner/app/Marshalling/ObjCTypesTests.js
  tests/TestRunner/app/Marshalling/PointerTests.js
  tests/TestRunner/app/Marshalling/Primitives/Function.js
  tests/TestRunner/app/Marshalling/ReferenceTests.js
  tests/TestRunner/app/Modules/index.js
  tests/TestRunner/app/ObjCConstructors.js
Labels: cla: yes, improvement, in progress

#1194 chore: Update CHANGELOG for 6.1.0
  CHANGELOG.md
Labels: cla: yes

#1192 fix: fix a memory leak
  src/debugging/TNSDebugging.h
Labels: cla: yes

#1195 fix: notify for AppRefreshStarted and remove the log for successful refresh request
  src/debugging/TNSDebugging.h
Labels: cla: yes, improvement
